-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 09:08:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemadcuv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemadcuv` ;

-- -----------------------------------------------------
-- Schema sistemadcuv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemadcuv` DEFAULT CHARACTER SET utf8mb4 ;
USE `sistemadcuv` ;

-- -----------------------------------------------------
-- Table `sistemadcuv`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(250) NULL,
  `estado` VARCHAR(45) NULL,
  `Desarrollador_idDesarrollador` INT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `sistemadcuv`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`Archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Archivo` (
  `idArchivo` INT NOT NULL AUTO_INCREMENT,
  `nombreArchivo` VARCHAR(100) NULL,
  `archivo` VARCHAR(45) NULL,
  `Cambio_idCambio` INT NULL,
  `SolicitudDeCambio_idSolicitudDeCambio` INT NULL,
  `Defecto_idDefecto` INT NULL,
  `Actividad_idActividad` INT NULL,
  PRIMARY KEY (`idArchivo`),
  INDEX `fk_Archivo_Cambio1_idx` (`Cambio_idCambio` ASC) VISIBLE,
  INDEX `fk_Archivo_SolicitudDeCambio1_idx` (`SolicitudDeCambio_idSolicitudDeCambio` ASC) VISIBLE,
  INDEX `fk_Archivo_Defecto1_idx` (`Defecto_idDefecto` ASC) VISIBLE,
  INDEX `fk_Archivo_Actividad1_idx` (`Actividad_idActividad` ASC) VISIBLE,
  CONSTRAINT `fk_Archivo_Cambio1`
    FOREIGN KEY (`Cambio_idCambio`)
    REFERENCES `sistemadcuv`.`Cambio` (`idCambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Archivo_SolicitudDeCambio1`
    FOREIGN KEY (`SolicitudDeCambio_idSolicitudDeCambio`)
    REFERENCES `sistemadcuv`.`SolicitudDeCambio` (`idSolicitudDeCambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Archivo_Defecto1`
    FOREIGN KEY (`Defecto_idDefecto`)
    REFERENCES `sistemadcuv`.`Defecto` (`idDefecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Archivo_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `sistemadcuv`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`Cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Cambio` (
  `idCambio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(250) NULL,
  `esfuerzo` INT NULL,
  `estado` VARCHAR(20) NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `impacto` VARCHAR(250) NULL,
  `razonCambio` VARCHAR(250) NULL,
  `tipo` VARCHAR(250) NULL,
  `Desarrollador_idDesarrollador` INT NULL,
  PRIMARY KEY (`idCambio`),
  INDEX `fk_Cambio_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC) VISIBLE,
  CONSTRAINT `fk_Cambio_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `sistemadcuv`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`Defecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Defecto` (
  `idDefecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo` VARCHAR(100) NULL,
  `fechaReporte` DATE NULL,
  `estado` VARCHAR(20) NULL,
  `esfuerzo` INT NULL,
  `descripcion` VARCHAR(250) NULL,
  `Desarrollador_idDesarrollador` INT NULL,
  PRIMARY KEY (`idDefecto`),
  INDEX `fk_Defecto_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC) VISIBLE,
  CONSTRAINT `fk_Defecto_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `sistemadcuv`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`Desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Desarrollador` (
  `idDesarrollador` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(200) NULL,
  `semestre` INT NULL,
  `matricula` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Proyecto_idProyecto` INT NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idDesarrollador`),
  INDEX `fk_Desarrollador_Proyecto1_idx` (`Proyecto_idProyecto` ASC) VISIBLE,
  CONSTRAINT `fk_Desarrollador_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `sistemadcuv`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`idProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`ResponsableDelProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`ResponsableDelProyecto` (
  `idResponsableDelProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(100) NULL,
  `numeroDePersonal` INT NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Proyecto_idProyecto` INT NULL,
  PRIMARY KEY (`idResponsableDelProyecto`),
  INDEX `fk_ResponsableDelProyecto_Proyecto1_idx` (`Proyecto_idProyecto` ASC) VISIBLE,
  CONSTRAINT `fk_ResponsableDelProyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `sistemadcuv`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadcuv`.`SolicitudDeCambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadcuv`.`SolicitudDeCambio` (
  `idSolicitudDeCambio` INT NOT NULL AUTO_INCREMENT,
  `nombreSolicitudDeCambio` VARCHAR(100) NULL,
  `descripcion` VARCHAR(250) NULL,
  `numeroSolicitud` INT NULL,
  `razon` VARCHAR(250) NULL,
  `estatus` VARCHAR(20) NULL,
  `fechaCreacion` DATE NULL,
  `fechaDeAprobacion` DATE NULL,
  `impacto` VARCHAR(250) NULL,
  `accionPropuesta` VARCHAR(250) NULL,
  `Desarrollador_idDesarrollador` INT NULL,
  `ResponsableDelProyecto_idResponsableDelProyecto` INT NULL,
  PRIMARY KEY (`idSolicitudDeCambio`),
  INDEX `fk_SolicitudDeCambio_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC) VISIBLE,
  INDEX `fk_SolicitudDeCambio_ResponsableDelProyecto1_idx` (`ResponsableDelProyecto_idResponsableDelProyecto` ASC) VISIBLE,
  CONSTRAINT `fk_SolicitudDeCambio_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `sistemadcuv`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudDeCambio_ResponsableDelProyecto1`
    FOREIGN KEY (`ResponsableDelProyecto_idResponsableDelProyecto`)
    REFERENCES `sistemadcuv`.`ResponsableDelProyecto` (`idResponsableDelProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
